'use client';
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import SimpleBottomNavigation from "@/components/bottomNavigation";
import { ThemeProvider } from "@emotion/react";
import { createTheme } from "@mui/material";
import { green, blue } from '@mui/material/colors';
import { Suspense } from "react";

// const montserrat = localFont({
//   src: "./fonts/montserrat/Montserrat-Bold.ttf",
//   variable: "--font-montserrat",
//   weight: "100 900"
// })

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };



export default function RootLayout({ children }) {
  const myTheme = createTheme({
    palette: {
      primary: {
        main: "#2700b6"
      },
      secondary: {
        main: "#1c931d"
      }
    },
    typography: {
      fontFamily: [
        // '--font-montserrat'
      ].join(','),
    },
  })

  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`--font-montserrat antialiased`}
      >
        <ThemeProvider theme={myTheme}>
          <Navbar />
          <div className="h-24"></div>
          {children}
          <div className="h-16"></div>
          <SimpleBottomNavigation />
        </ThemeProvider>
      </body>
    </html>
  );
}
