
import Head from "next/head";
import "./globals.css";
import Home from "./home";

// const montserrat = localFont({
//   src: "./fonts/montserrat/Montserrat-Bold.ttf",
//   variable: "--font-montserrat",
//   weight: "100 900"
// })

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const viewport = {
  themeColor: "blue"
}

export const metadata = {
  title: {
    'template': '%s | Blagus',
    'default': 'Home'
  },
  description: "Generated by create next app",
  // themeColor: "primary"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`--font-montserrat antialiased`}
      >
        <Home>
          {children}
        </Home>
      </body>
    </html>
  );
}
